### ISSUE TITLE
Empty calendar results in 404 error

### ISSUE THREAD

**Issue by hrehfeld** [dengste/org-caldav#109]
If I create a new calendar in nextcloud and then try to sync org entries to it:

    Contacting host: myhost:443
    Putting event 1 of 10
    Putting event 2 of 10
    Putting event 3 of 10
    Putting event 4 of 10
    Putting event 5 of 10
    Putting event 6 of 10
    Putting event 7 of 10
    Putting event 8 of 10
    Putting event 9 of 10
    Putting event 10 of 10
    org-caldav-get-event-etag-list: Error while getting eventlist from https://myhost/remote.php/dav/calendars/myuser/mycal/. Got status code: 404.

**Workaround**: When I put an event into the calendar from the webinterface, it just works.

**Comment by eqyiel** [comment]
I'm seeing this too.

@hrehfeld thanks for the workaround.

**Comment by dengste** [comment]
It seems some CalDAV servers return 404 when doing PROPFIND on a newly created calendar which was not yet used. I changed to code to simply accept this. Please reopen if that is not helping.

**Comment by grauschnabel** [comment]
the workarround does not help for me.  please reopen...
```
if: Error while getting eventlist from https://myhost/cloud/remote.php/dav/calendars/martin@mydomain/Work/. Got status code: 404.
```
Sounds a bit different, but I think its the same

**Comment by grauschnabel** [comment]
ok, dont reopen it.  I found out that owncloud does put uppercase letters to lowercase for the calendar-id.  so it works now.

**Comment by grauschnabel** [comment]
i found out that owncloud puts uppercase letters to lowercase, so I use lowercase as calendar-id, so this works now.

**Comment by grauschnabel** [comment]
Them I have another extra information. If you add a calendar to owncloud from a third party app, the id can be very different to the calendars name. I tried this with the business calendar 2 on android, the calender is looks a bit similar to org-mode autogenerated ID's. But there is a way to see the calendar url, where the id is the last part of the url.

**Comment by dengste** [comment]
Thanks again. I've rewritten the part in the Readme to mention this.
