### ISSUE TITLE
org-caldav just deleted my entire remote calendar

### ISSUE THREAD

**Issue by floli** [dengste/org-caldav#113]
Hello,
I set up org-caldav:
```
(use-package org-caldav
  :ensure t
  :config (setq org-caldav-url "https://invalid.de/cloud/remote.php/dav/calendars/foli"
                org-caldav-calendar-id "sgskalender_shared_by_franzefn"
                org-caldav-inbox (concat org-directory "/sgs.org")
                org-icalendar-timezone "Europe/Berlin"
                org-caldav-files nil)
)
```
created an empty sgs.org and called ```org-caldav-sync```. org-caldav now started to delete my entire remote calendar, which was definitely unwanted :-/

Can I configure org-caldav to never touch the remote calendar?

Does setting
```
                org-caldav-sync-changes-to-org 'all
                org-caldav-delete-org-entries 'always
```
has this effect?

**Comment by dengste** [comment]
I cannot reproduce this. org-caldav should only delete an event in a calendar if its ID used to be in an Org file but now isn't anymore. So the only way I can see this happening is when the events in that calendar were synced with org-caldav in the first place, but then you synced again with org-caldav-files set to nil, which would make it look like you deleted the events on the Org side.
Currently there's no way to never delete anything on the calendar side, but it would probably make sense to have a variable for that. 
It would probably also make sense to detect that org-caldav-files has changed between syncs. I have to think about that.

**Comment by dengste** [comment]
I've now added that org-caldav should detect when you remove Org files between two syncs and warn you accordingly. Also, you can now do

    (setq org-caldav-delete-calendar-entries 'never)

and calendar events will never get deleted (alternatively, you can use 'ask).
