### ISSUE TITLE
Reoccuring events

### ISSUE THREAD

**Issue by floli** [dengste/org-caldav#114]
Hello,
I have an event:

```
BEGIN:VEVENT
CREATED:20160126T130850Z
LAST-MODIFIED:20170418T152123Z
DTSTAMP:20170418T152123Z
UID:a63ecaef-d8da-4c58-ada6-7432f0ca111b
SUMMARY:MM\, FL\, KS: preCICE TelCo
STATUS:CONFIRMED
RRULE:FREQ=WEEKLY
EXDATE:20160928T090000Z
EXDATE:20161012T090000Z
EXDATE:20161102T100000Z
EXDATE:20161228T100000Z
EXDATE:20170104T100000Z
EXDATE:20170111T100000Z
EXDATE:20170419T084500Z
DTSTART;TZID=Europe/Berlin:20160203T104500
DTEND;TZID=Europe/Berlin:20160203T114500
CLASS:PUBLIC
SEQUENCE:8
TRANSP:OPAQUE
X-MOZ-GENERATION:16
END:VEVENT
```
which is synced to:
```
* MM, FL, KS: preCICE TelCo
:PROPERTIES:
:ID:       Nextcloud-404ZYXCREWKQD5M7MARF3
:END:
  <2016-02-03 Mi 10:45-11:45>
```
So it seems that the value from ```DTSTART``` is taken and the repeating events are ignored.

Is that a known issue?

For me, it would be also ok, if a reoccuring event is simply created multiple times in the org file. (which would require setting a synced time span, so it doesn't get created infinitely)

**Comment by dengste** [comment]
Yes, it's a known issue, see Readme.

**Comment by floli** [comment]
Ok, that's a pity, for me it's an absolute must-have feature.

**Comment by dengste** [comment]
It's a complicated problem. I might look at it when I have transformed the code to use org-element. It might be more feasible to implement then, I'll have a look.
