### ISSUE TITLE
Enhancement: VTODO

### ISSUE THREAD

**Issue by grauschnabel** [dengste/org-caldav#118]
Using `org-icalendar-include-todo` makes org-icalendar-export to include my todos as VTODO entries.  Nextcloud also supports this VTODO entries having an extra app, called Tasks to handle that.

Also davdroid (mobile app android) syncs that so on mobile we can use calendar as usual and tasks via Mobile Apps Davdroid (for syncing) and OpenTasks (for editing).

The only missing link to org-mode is a tool that takes the TODO entries and syncs it to the nextcloud.

At the moment, if you have tasks in your nextcloud, org-caldav-sync loads that from the server but cannot handle this, you see
```
CalDAV Sync finished.

== Sync errors: 

UID: Nextcloud-ouy6sii0hnn0ga25lx83h9i
   Title: (Could not find UID)
   Status: error  Action: error:inbox-notfound
   Calendar: work


== Successful syncs: 

None.
```
And it creates an entry in the org file like:
* No Title
(without any PROPERTIES)

Would be nice to create a * TODO entry in the org file
And on the other hand just to upload VTODO entries as well as the VEVENT entries which come from org-icalendar-export when including todo entries.

I would recommend to set an extra inbox for todo entries like `:inbox (id "somehwere") :inbox-todo (id "somewhereelse")` for multiple calendars.

I don't know how much work that is, but I would like to help if you can tell me how to start.

**Comment by grauschnabel** [comment]
I made a fork, see https://github.com/grauschnabel/org-caldav this should fit for the most issues.
For my setting it is stable, please check it out and report issues there.  I will make a pull request when it is stable for other people too.  And tell me enhancements.

To test: the best way I think is to keep your org files in a git repository, so you see what will be changed, when using that.  Make sure you have backups.

@dengste: would you recommend this feature?  I think it would be the best way to sync org-mode with an android mobile phone.

**Comment by whirm** [comment]
I've just set it up and it seems to be working fine. It would be great to have it merged upstream!

**Comment by grauschnabel** [comment]
Please tell me, do you use it with nextcloud or something else? Which version? An do you also sync it somewhere else?

**Comment by whirm** [comment]
Server side: Nextcloud, latest stable with Calendar and Tasks apps
Laptop: Emacs 25 with your fork of org-caldav
Phone: DAVdroid (1.9-ose) + OpenTasks (1.1.9) from F-Droid repos.

**Comment by whirm** [comment]
I'll play with it a bit more and see if there's no data loss. If I find any issue I'll report it.

**Comment by grauschnabel** [comment]
Thanks

**Comment by jackkamm** [comment]
Merged now, thanks for this!
