### ISSUE TITLE
duplicates with multiple (>2) calendars

### ISSUE THREAD

**Issue by gour** [dengste/org-caldav#135]
Hello,

in the past I was using org-caldav package to sync my calendar (and contacts) entries with my Android phones via Baikal server, but at some point it got broken - see #51, so I had to another solution by using vdiryncer.

Recently, I found out that org-caldav is supposed to work (again) with multiple calendars, but I must admit it's not clear how one is supposed to configure `:skip-conditions` function?

I have a need for 4 or 5 calendars: my own, one for wife's activities, one for the kid's, another using special calendar, birthdays...

I did try with this setup:

* added required calendars to my org-agenda-files, like:

```
  (setq org-agenda-files
        (list "~/emacs/org/gour.org"
              "~/emacs/org/wife.org"
              "~/emacs/org/kid.org"
              "~/emacs/org/special.org"
              "~/emacs/org/birthdays.org"
              "~/emacs/org/calendar.org"
              )
```

and I want that calendar.org does contain all the entries which do arrive from the Android phones.

* here is org-caldav's part of setup:

```
  (setq org-caldav-calendars
        '((:calendar-id "gour" :files ("~/emacs/org/gour.org")
                        :inbox "~/emacs/org/calendar.org")

          (:calendar-id "jahnava" :files ("~/emacs/org/wife.org")
                        :inbox "~/emacs/org/calendar.org")

          (:calendar-id "kirtana" :files ("~/emacs/org/kid.org")
                        :inbox "~/emacs/org/calendar.org")

          (:calendar-id "vaishnava" :files ("~/emacs/org/special.org")
                        :inbox "~/emacs/org/calendar.org")
          
          (:calendar-id "birthdays" :files ("~/emacs/org/birthdays.org")
                        :inbox "~/emacs/org/calendar.org")
          )
        )
```

So, I'd like to enter calendar entries for myself into gour.org and, similarly to other adequately named *.org files, while calendar.org should contain entries which were entered on the phone(s) and were
synced with my org files.

However, when I tried the above setup, one of the calendar got all the duplicates from another, in my case, kid.org got all the entries from wife.org.

Anyone can suggest how to incorporate `:skip-conditions` so that there won't by any duplicates and every for every entry in my agenda it will be clear where the entry does belong to?

In the test-suite I've noticed the following: `:skip-conditions (notregexp ":sometag:")`

so maybe the setup could be done by adding specific tags (eg. ":kid:", ":wife:" etc. to the setup, but it's not clear to me how to configure everything for more than two calendars and/or what is the reason that `org-caldav` creates duplicated entries?

**Comment by TRSx80** [comment]
I think what you want to do is first create separate calendars on the CalDAV end. Then get the names of those calendars and use them in your config. Then you either tag your entries or use separate files. It seems you have the Org end set up mostly, just need to set up the CalDAV end. :)

**Comment by dengste** [comment]
I guess you need to use different inboxes for the calendars, since those are synced as well. Every item in org-caldav-calendars starts its own independent sync run, so the sync for 'kirtana' wouldn't know that the entries in the calendar.org are from the 'jahnava' calendar. Another possibility would be to use tags, but it's more complicated.

**Comment by dengste** [comment]
You can disable syncing of the inbox now by setting :sync-inbox to nil.

**Comment by dengste** [comment]
I reverted that because this leads to events getting deleted on the next sync.

So I think you need to use different inboxes for the different calendars. I'm also thinking of automating a tag-based solution.
