### ISSUE TITLE
Time ranges are not updated properly

### ISSUE THREAD

**Issue by wyleyr** [dengste/org-caldav#137]
In an Org entry with a time stamp range like `<2018-04-03>--<2018-04-05>`, updating the start date on the caldav server to April 4 and syncing back to Org results in a malformed range like `<2018-04-04>--<2018-04-05>--<2018-04-05>`.  That is, only the first date of the range is replaced.

The problem seems to be that `org-caldav-change-timestamp` only matches against single timestamps, not time ranges.

**Comment by alexozer** [comment]
Can this be closed?

**Comment by wyleyr** [comment]
Yes, I believe so...I haven't had any further issues!
