### ISSUE TITLE
org-caldav does not sync, when using multiple calendars and one of them is empty

### ISSUE THREAD

**Issue by knatsakis** [dengste/org-caldav#139]
When using multiple calendars and one of them is empty, then syncing does not work for subsequent calendars, or when running org-caldav-sync for the second time.

It seems that 'org-caldav-empty-calendar is not reset from calendar to calendar. When an empty calendar is encountered, the value 'org-caldav-empty-calendar is set to true and the value persists when syncing subsequent calendars.

**Comment by knatsakis** [comment]
Please review pull request #140 for a proposed (partial?) fix to this issue.

**Comment by knatsakis** [comment]
Please review pull request #169 which supersedes PR #140 (use knatsakis/org-caldav branch org-caldav-empty-calendar as head fork instead of master)

**Comment by dengste** [comment]
#169 is merged.
