### ISSUE TITLE
Unable to resolve link on when  "brain" link types are present 

### ISSUE THREAD

**Issue by usharf** [dengste/org-caldav#147]
I'd like to keep notes under the heading of some activites, and I've noticed that if try to link using `org-brain` links, which look like this:

```
brain:fbc84dd4-571b-4b70-a181-da131ccba067
```

`org-caldav` will faill to sync:

```
user-error: Unable to resolve link: "brain:fbc84dd4-571b-4b70-a181-da131ccba067"

```

**Comment by grauschnabel** [comment]
Not supported, sorry.

**Comment by usharf** [comment]
Ok. Is it possible though, or is it `org-icalendar` that's complaining?

**Comment by thisirs** [comment]
Try `(setq org-export-with-broken-links 'mark)`

**Comment by usharf** [comment]
thanks a lot. that solved the problem for me.
