### ISSUE TITLE
Please consider moving the project elsewhere. 

### ISSUE THREAD

**Issue by ghost** [dengste/org-caldav#149]
I will be closing my account here following the purchase by Microsoft as I’m sure many other will as well.

https://monitor.gitlab.net/dashboard/db/github-importer?orgId=1

**Comment by grauschnabel** [comment]
I didn't see that issue before. Any other links to see the background?

What do you think about gitlab?

**Comment by usharf** [comment]
Well, I think they’re good enough, especially being able to federate their server. 

Problem is Microsoft buying github. I think Menno open source developers will have a problem with that, considering Microsoft is so aggressively pushing their own tools and products, and can’t be considered impartial. 

There’s a good explanation by RMS what is required of these type of systems to be variable long term for open source projects.

**Comment by alphapapa** [comment]
@ghost While I'm not happy about the acquisition, and I can't stand Microsoft, it's not friendly for you to tell other people where they should host their projects, especially with some kind of implied threat about your not participating anymore unless they do what you want.
