### ISSUE TITLE
Can it work with iCloud Calendar?

### ISSUE THREAD

**Issue by raxod502** [dengste/org-caldav#151]
I am able to sync my iCloud Calendar with Thunderbird by extracting a read/write CalDAV URL for it following [these instructions](https://frightanic.com/apple-mac/thunderbird-icloud-calendar-sync/).

I figured that maybe it would work with `org-caldav` as follows:

    (setq org-caldav-url "https://p22-caldav.icloud.com/<user-id>/calendars/<calendar-id>/")
    (setq org-caldav-calendar-id "<calendar-id>")
    
Unfortunately, on running `M-x org-caldav-sync`, I get:

    HTTP/1.1 400 Bad Request
    Server: AppleHttpServer/2f080fc0
    Date: Wed, 13 Jun 2018 02:20:43 GMT
    Content-Type: text/html
    Content-Length: 185
    Connection: close

    <html>
    <head><title>400 Bad Request</title></head>
    <body bgcolor="white">
    <center><h1>400 Bad Request</h1></center>
    <hr><center>AppleHttpServer/2f080fc0</center>
    </body>
    </html>

Is that expected behavior?

**Comment by nanzhong** [comment]
Have you tried using `https://p22-caldav.icloud.com/<user-id>/calendars/<calendar-id>/user` as the `org-caldav-url`?

**Comment by raxod502** [comment]
No, I didn't try that, and by now I've switched to a different calendar syncing solution—sorry.

If that URL format works, then perhaps it can be added to the documentation :)
