### ISSUE TITLE
org-caldav-skip-conditions not working

### ISSUE THREAD

**Issue by TRSx80** [dengste/org-caldav#154]
FWIW, I was going to title this "I can't seem to get org-caldav-skip-conditions to work" because my first assumption is that *I* am doing something wrong, however I put the above instead for better search keywords, in case anyone else has the same issue. ;)

As stated in the source, I have studied the documentation of the Org built in variable `org-agenda-skip-if`and I have the following in my Emacs Init File:

`(setq org-caldav-skip-conditions '('todo 'done))`

...which I *believe* is correct because I can evaluate it with C-x C-e without error. And I can execute `org-caldav-sync` also without error. However if I change one of my calendar headline items from TODO to DONE for instance, it just updates the entry (because I changed it) but does not exclude it from the export.

I even tried a direct quote of `"DONE"` instead of the token `'done`. That didn't work either. And neither did putting it into a list like `'('todo '("DONE"))` etc.

**Comment by dengste** [comment]
This is merged now.

**Comment by kahironimashte** [comment]
I am not able to prevent org-caldav from syncing headings with the DONE keyword using the same `(setq org-caldav-skip-conditions '('todo 'done))` as @TRSx80. 

I use the lates MELPA-package on emacs 26.3. 

```
﻿org-caldav-skip-conditions is a variable defined in ‘org-caldav.el’.
Its value is ('todo 'done)
Original value was nil
``` 

Is this actually correct?

**Comment by Bergschrat1** [comment]
Yes, same problem for me. No done-keywords are skipped. The entry is just changed.
With the same settings:
`(setq org-caldav-skip-conditions '('todo 'done))`
