### ISSUE TITLE
FAQ Document

### ISSUE THREAD

**Issue by DaoHuyTuan** [dengste/org-caldav#163]
i'm reading the document but still not understand about "symbol google" can you explain more easy to understand what i must put in org-caldav-url ?? . I'm trying to connect org with my google calendar 
Thanks

**Comment by mgttlinger** [comment]
As far as "symbol google" goes this means `'google` as far as I know

**Comment by DaoHuyTuan** [comment]
thanks @mgttlinger , but i follow that still can't connect with google calendar @@ may be i miss something on config
