### ISSUE TITLE
Format string error when syncing

### ISSUE THREAD

**Issue by mgttlinger** [dengste/org-caldav#164]
When trying to sync I get the following error:

```elisp
(:calendar-id "exam" :inbox "/workspace/calendars/exam.org")
Check connection for https://correct_but_censored_url/exam/.
Got error while checking connection (will try again):
(error "Not enough arguments for format string")
``` 

Where should I dig to track this issue down?

**Comment by niclasborlin** [comment]
The string appears in `org-caldav-sync-calendar` near line 801, so I'd do an edebug of `org-caldav-sync-calendar`, hoping to replicate it.

**Comment by mgttlinger** [comment]
Ok, tracked the issue down to a debugging `(message)` I had inserted printing the received XML which contained a `%`
