### ISSUE TITLE
Does not accept DAV requestions

### ISSUE THREAD

**Issue by psmith1303** [dengste/org-caldav#165]
I'm trying to get org-caldav working against fastmail.com
My test setup looks like this:

```
(require 'org-caldav)

;; The CalDAV URL with your full and primary email address at the end.
(setq org-caldav-url "https://caldav.fastmail.com/dav/calendar/user/mail@petersmith.org")

;; The name of your calendar, typically "Calendar" or similar
;; Running
(setq org-caldav-calendar-id "d7b665c1-5232-4b01-9ad2-8d2a4ada11ab")

;; Local file that gets events from the server
(setq org-caldav-inbox "~/NAS/Org/diary.org")

;; never delete anything at the CALDAV end
(setq org-caldav-delete-calendar-entries 'never)

;; Debug like crazy
(setq org-caldav-debug-level 2)

;; List of your org files here
;; (setq org-caldav-files org-agenda-files)

;; Please make sure to set your correct timezone here
(setq org-icalendar-timezone "Pacific/Auckland")
(setq org-icalendar-date-time-format ";TZID=%Z:%Y%m%dT%H%M%S")
```

After being prompted for my username and password, I get an error that says

> Contacting host: caldav.fastmail.com:443 [2 times]
org-caldav-check-dav: The URL https://caldav.fastmail.com/dav/calendar/user/mail@petersmith.org/d7b665c1-5232-4b01-9ad2-8d2a4ada11ab/ does not accept DAV requests

and a buffer that looks like:

> HTTP/1.1 200 OK

> Server: nginx
> Date: Sun, 28 Oct 2018 04:33:07 GMT
> Content-Length: 0
> Connection: keep-alive
> Cache-Control: no-cache
> Allow: OPTIONS, GET, HEAD
> Content-Disposition: attachment
> X-Frontend: frontend1
> Content-Security-Policy: default-src 'none';
> 

If I run this debugging code:
```
(switch-to-buffer (let ((url-request-method "OPTIONS")
 (url-request-data nil)) (url-retrieve-synchronously
 "https://caldav.fastmail.com/dav/calendars/user/mail@petersmith.org/d7b665c1-5232-4b01-9ad2-8d2a4ada11ab/")))
```

I get:

> HTTP/1.1 200 OK
> Server: nginx
> Date: Sun, 28 Oct 2018 04:35:09 GMT
> Content-Length: 0
> Connection: keep-alive
> Link: </dav/principals/.server-info>; rel="server-info"; token="d37244af03de852701d82c5c224adec41c983bac"
> Link: </dav/calendars/user/mail@petersmith.org/d7b665c1-5232-4b01-9ad2-8d2a4ada11ab/>; rel="subscribe-caldav_auth"
> Link: </dav/calendars/user/mail@petersmith.org/d7b665c1-5232-4b01-9ad2-8d2a4ada11ab/>; rel="subscribe-webdav_sync"
> Link: </dav/calendars/user/mail@petersmith.org/d7b665c1-5232-4b01-9ad2-8d2a4ada11ab/>; rel="subscribe-enhanced-get"
> Cache-Control: no-cache
> DAV: 1, 2, 3, access-control, extended-mkcol, resource-sharing
> DAV: calendar-access, calendar-auto-schedule
> DAV: calendar-query-extended, calendar-availability
> DAV: calendarserver-sharing, inbox-availability
> Allow: OPTIONS, GET, HEAD, POST, PUT, DELETE
> Allow: PROPFIND, REPORT, COPY, MOVE, PROPPATCH, LOCK, UNLOCK, ACL
> Content-Disposition: attachment
> X-Frontend: frontend1
> Content-Security-Policy: default-src 'none';

Which kind of looks right.

:scratches head:

Any clue as to what I'm doing wrong?

**Comment by psmith1303** [comment]
By the way, a simple

> wget  --http-user="mail@petersmith.org"  --http-password=xxxxxxxxxx https://caldav.fastmail.com/dav/calendars/user/mail@petersmith.org/d7b665c1-5232-4b01-9ad2-8d2a4ada11ab/

does retrieve the contents of calendar okay.

**Comment by dengste** [comment]
I guess you moved to something else by now, but in any case: I have no idea with this does not work. My only guess is that this is somehow related to an authentication issue, which does not correctly work the first time and hence you're not presented with DAV options.

**Comment by yiufung** [comment]
@psmith1303 In your elisp code, you used `calendar` instead of `calendars` in the URL. The subsequent requests use correct one so they worked. 

So Fastmail CalDAV works. @dengste you may consider adding support notice to README. Thanks for developing this great package

**Comment by psmith1303** [comment]
> @psmith1303 In your elisp code, you used `calendar` instead of `calendars` in the URL. The subsequent requests use correct one so they worked.
> 
Doh! Thank's for spotting that.
