### ISSUE TITLE
Authentication error with Google accounts

### ISSUE THREAD

**Issue by rgemulla** [dengste/org-caldav#171]
When trying to sync Google calenders, org-caldav recently started to show error "End of file while parsing JSON" and stopped synching. A quick fix is to set

```
(setq org-caldav-oauth2-providers
      '((google
         "https://accounts.google.com/o/oauth2/v2/auth"
         "https://www.googleapis.com/oauth2/v4/token"
         "https://www.googleapis.com/auth/calendar"
         "https://apidata.googleusercontent.com/caldav/v2/%s/events")))
```

Apparently, the Google's oauth2 URLs in org-caldav are not up-to-date.

**Comment by baspeeters** [comment]
Even with applying @rgemulla's sugestion, I still get `End of file while parsing JSON`.

\*Messages\*:
> Contacting host: www.googleapis.com:443
> json-read: End of file while parsing JSON

Even when I've set `org-caldav-debug-level` to `2`, the debug buffer only displays a syncing message:

\*org-caldev-debug-buffer\*:
> ========== Started sync

The only thing which has happened is the creation of an empty `appointments.org`.

Is there a way to get some more detail about which data `json-read` is handling?

**Comment by felipelalli** [comment]
I'm getting this error "End of file while parsing JSON" when trying to sync.
