### ISSUE TITLE
Unable to sync with Nextcloud

### ISSUE THREAD

**Issue by nrdsp** [dengste/org-caldav#178]
Getting "400 The plain HTTP request was sent to HTTPS port" as a response and "Error while checking for OPTIONS at URL https://my-nextcloud.server/remote.php/dav/calendars/userid: 400 Bad Request". I wonder if it's due to some change in Nextcloud? I have the latest stable version of Nextcloud installed, 16.0.1 ([changelog here](https://github.com/nextcloud/vm/releases)). Everything worked well until just a couple of days ago. Here's the full response:

    HTTP/1.1 400 Bad Request
    Server: nginx
    Date: Sat, 22 Jun 2019 08:50:22 GMT
    Content-Type: text/html
    Content-Length: 264
    Connection: close

    <html>
    <head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
    <body bgcolor="white">
    <center><h1>400 Bad Request</h1></center>
    <center>The plain HTTP request was sent to HTTPS port</center>
    <hr><center>nginx</center>
    </body>
    </html>

I do not have TOTP currently enabled on the Nextcloud server for this user, nor did I ever set a `authinfo` file. Also, when I do `curl -D - -X OPTIONS --basic -u userid:mypassword https://my-nextcloud.server/remote.php/dav/calendars/userid`, I do get a`HTTP/2 200` response and the following header:

    dav: 1, 3, extended-mkcol, access-control, calendarserver-principal-property-search, calendar-access, calendar-proxy, calendar-auto-schedule, calendar-availability, nc-calendar-webcal-cache, calendarserver-subscribed, oc-resource-sharing, oc-calendar-publishing, calendarserver-sharing, nc-calendar-search, nc-enable-birthday-calendar

**Comment by grauschnabel** [comment]
You can fix that by using "ssl off" in your nginx config. This should fix it right now. I know this is not the best solution. Hope we get it on the client somehow.

**Comment by nrdsp** [comment]
Will have to wait for the client solution, I'm afraid, as I don't have access to the nginx config. I'm using a Hetzner pre-installed server. Thank you for pointing out the issue though, I tried everything I could possibly remember, to no avail obviously!

**Comment by grauschnabel** [comment]
I'm searching for the solution, but maybe someone know what to do?

When I run
```
(let ((url-request-method "OPTIONS")
        (auth-sources '((:source "~/.authinfo" :host t :protocol t)))
        (url "https://<myserver>/cloud/remote.php/dav/calendars/<userid>/work/"))
  (url-retrieve url
    (lambda (status) (switch-to-buffer (current-buffer)))))
```
before i use `org-caldav-sync`, the sync for all my calendars (there are 4 now) works fine.  But dont using this, I fail like above.   @nrdsp could you try this (maybe in the scratch buffer) to see if its the same for you? (work is the calendar id))

**Comment by grauschnabel** [comment]
I was putting this in a function and run it everytime org-caldav-sync fails and then it works. But I'm not able to figure out what happens.  Any ideas?

**Comment by nrdsp** [comment]
@grauschnabel I confirm that running the above code works for me as well. Here's what I get:

    HTTP/1.1 200 OK
    Server: nginx
    Date: Fri, 28 Jun 2019 11:01:16 GMT
    Content-Type: text/html; charset=UTF-8
    Content-Length: 0
    Connection: keep-alive
    Expires: Thu, 19 Nov 1981 08:52:00 GMT
    Cache-Control: no-store, no-cache, must-revalidate
    Pragma: no-cache
    X-Frame-Options: SAMEORIGIN
    Content-Security-Policy: default-src 'none';
    Allow: OPTIONS, GET, HEAD, DELETE, PROPFIND, PUT, PROPPATCH, COPY, MOVE, REPORT
    DAV: 1, 3, extended-mkcol, access-control, calendarserver-principal-property-search, calendar-access, calendar-proxy, calendar-auto-schedule, calendar-availability, nc-calendar-webcal-cache, calendarserver-subscribed, oc-resource-sharing, oc-calendar-publishing, calendarserver-sharing, nc-calendar-search, nc-enable-birthday-calendar
    MS-Author-Via: DAV
    Accept-Ranges: bytes
    Strict-Transport-Security: max-age=15768000; includeSubDomains
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block
    X-Robots-Tag: none
    X-Download-Options: noopen
    X-Permitted-Cross-Domain-Policies: none
    Referrer-Policy: strict-origin

After running it, `org-caldav-sync` works just fine.

**Comment by grauschnabel** [comment]
this seems to be fixed in emacs 27.0.50 - for me this works. with emacs 26 I get this error. can you test this too @nrdsp ?

**Comment by dakra** [comment]
I had another look at this bug and it seems to be [this](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=34341) Emacs/TLS bug.

@nrdsp can you set this

``` emacs-lisp
(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")
```

and report if it works for you?

**Comment by nrdsp** [comment]
@dakra tt works perfectly with the variable `gnutls-algorithm-priority` set to `"NORMAL:-VERS-TLS1.3"`, thanks! @grauschnabel I didn't upgrade to emacs 27 yet. Therefore, still unable to report back on that but I will as soon as I upgrade.

**Comment by dengste** [comment]
I can at least confirm that upgrading to Emacs 26.2.90 lets me connect to Nextcloud 16 via TLSv1.3. I've added a note to the Readme, I don't think there's much more I can do, so I'm closing this. Thanks everyone for tracking this down.

**Comment by nrdsp** [comment]
Still unable to report as I'm still stuck with Emacs 26.2.17 but I re-confirm that @dakra [fix above](https://github.com/dengste/org-caldav/issues/178#issuecomment-510138795) does the trick when updating Emacs is not an option for some reason or another. Thanks all for the hints and fixes!
