### ISSUE TITLE
Maintenance of org-caldav

### ISSUE THREAD

**Issue by dakra** [dengste/org-caldav#179]
Hi @dengste 

thank you very much for `org-caldav`. I recently started using it but I had to apply a few patches first before I got it working. I see there are a lot of open issues and pull requests.

If you need help maintaining this package I would offer to look at PRs/issues etc and help out a bit. Just add me as a maintainer to this project.

Thanks.

(
I currently have a [fork here](https://github.com/dakra/org-caldav) with PRs
#141, #159, #161, #167, #169, #170 applied.
)

**Comment by whirm** [comment]
@dakra There's this other fork that's seen some activity: https://github.com/grauschnabel/org-caldav if @dengste is not responsive, maybe you and @grauschnabel could join efforts?

**Comment by dakra** [comment]
Thanks for the pointer.
I wasn't aware of that fork before I started mine.

Comparing seems a bit difficult as we both did a lot of
whitespace and other cleanup which makes the diff so noisy.
E.g. this is [@grauschnabel's fork](https://github.com/dengste/org-caldav/compare/master...grauschnabel:master) and this is [mine](https://github.com/dengste/org-caldav/compare/master...dakra:master)
And [this](https://github.com/grauschnabel/org-caldav/compare/master...dakra:master) is mine compared to @grauschnabel's.

Seems like @grauschnabel implemented syncing TODO items, while
I cleaned the code up a bit more (like removing old Emacs 24
kludge, adding customize interface and removing compiler/linter
warnings). Maybe I find a bit time to merge his todo change into
my fork (I didn't even know that you can sync todo items with caldav).

Looking at @dengste's GitHub history I'm afraid it looks like he
doesn't use this account anymore :(

I'm not sure about the appropriate next steps.
I'm happy with simply using my own fork, but maybe it makes
sense to put @grauschnabel or mine also on melpa so
more people are aware of it.

**Comment by grauschnabel** [comment]
I'm right now working on merging your changes to mine, @dakra.  I'm a bit confused of your changes by taking the oauth2 things out to another file.  So I need some time.  Maybe not all your changes come into mine, we will se.

**Comment by dakra** [comment]
>  I'm a bit confused of your changes by taking the oauth2 things out to another file.

I did that because I don't use google calendar and this way the `oauth2` package is not a requirement. `org-caldav-oauth2` could basically be a separate addon package.

**Comment by whirm** [comment]
I don't have much free time but let me know if you could use some help sanitizing the commits whitespace wise to make merging easier.

**Comment by dengste** [comment]
Hi there,
sorry for the hiatus. I'm on holiday now and will try to get up to speed...

**Comment by dakra** [comment]
>  sorry for the hiatus. I'm on holiday now and will try to get up to speed...

No worries. As in my original post, if you want support from time to time you can add me (and/or @grauschnabel / @whirm ?) as maintainer here and I'll help when I can.

I'm closing this now as it seems you're back :)
