### ISSUE TITLE
"Format specifier doesn’t match argument type" after changing item and syncing

### ISSUE THREAD

**Issue by jtwil** [dengste/org-caldav#184]
Caused by the line 
`(org-caldav-debug-print 1 (format "UID %s: Got sequence number %d" (car event) seq))`
in `org-caldav-set-sequence-number`.

It seems Nextcloud calendar doesn't add "SEQUENCE" entries to its calendar items, hence `seq` is nil. PR #128 has highlighted this error, with its assumption `seq` is a number. Changing the "%d" in the line above to "%s" avoids the error. But, is it appropriate for `org-caldav-set-sequence-number` to set `seq` to 1, if `(org-caldav-event-sequence event)` is nil?

**Comment by dengste** [comment]
Thanks, PR #128 indeed showed that there is a bug for events without a sequence number.
