### ISSUE TITLE
Sync errors from Nextcloud 16

### ISSUE THREAD

**Issue by Spass1966** [dengste/org-caldav#186]
Literally any event created within Nextcloud and then synced using `org-caldav-sync` all-day or with a time errors with the following:

```
CalDAV Sync finished.

== Sync errors: 

UID: Nextcloud-SE0KEWDRH22IVGQRVC4VC
   Title: (Could not find UID)
   Status: error  Action: error:inbox-notfound


== Successful syncs: 

None.
```

I don't have Tasks set-up.

**Comment by dengste** [comment]
> Status: error  Action: error:inbox-notfound

This means whatever you defined as your inbox could not be found.

**Comment by Spass1966** [comment]
> > Status: error  Action: error:inbox-notfound
> 
> This means whatever you defined as your inbox could not be found.

` (setq org-caldav-files `("~/org/inbox.org"))`

```
$USER@arha ~> ls ~/org/inbox.org 
/home/$USER/org/inbox.org
```
 What am I not getting here?

**Comment by dengste** [comment]
See Readme on variables org-caldav-files  and org-caldav-inbox.
