### ISSUE TITLE
org-maybe-keyword-time-regexp removed in Org mode 9.4

### ISSUE THREAD

**Issue by dinojr** [dengste/org-caldav#206]
Last updates to org-mode seem to break org-caldav synchronisation. I get the following error message:
`org-caldav-update-events-in-org: Symbol’s value as variable is void: org-maybe-keyword-time-regexp`
The release notes for org-mode 9.4 mention:
```
Removed  ~org-maybe-keyword-time-regexp~
The variable was not used in the code base.
```

**Comment by hughwilliams94** [comment]
I have written a PR (#207) to fix this (following some advice from the orgmode mailing list). It seems to work on my setup, please feel free to use my branch until the request gets merged.

**Comment by dengste** [comment]
PR was merged
