### ISSUE TITLE
Use ":user" when calling auth-source-search

### ISSUE THREAD

**Issue by benneti** [dengste/org-caldav#222]
I have several different users for the url my nextcloud is located and as such I believe I get invalid username and pass because :user is not used in the query.

I did not find the call directly but in the logs it seem the search only uses the host and if I replicate the query I get the wrong secret.

**Comment by benneti** [comment]
actually this is a problem in urllib and can be worked around by setting the password in the url (can be hacked together with auth-info)

**Comment by dinojr** [comment]
How can you hack it if the credentials are stored in password-store ?
