### ISSUE TITLE
Possible To Sync with baikal or radicale

### ISSUE THREAD

**Issue by mourningsun75** [dengste/org-caldav#25]
Hi,

thanks for your great sync script. But is it possible to add support for baikal (http://baikal-server.com/) or radicale (http://radicale.org/) calendar?

I only use the oversized owncloud app because of org-caldav....

Would be great!

with best
Daniel

**Comment by occidens** [comment]
I am not able to sync with either Radicale or Baikal. Does anyone have any hints on how to get this to work. Or perhaps some new incompatibilities have arisen in the latest versions? (I understand that the CalDAV protocol is complex and that there are a lot of variations between server implementations).

- With Radicale, I get the error "Error while getting eventlist" when syncing, as described in [this thread] (http://thread.gmane.org/gmane.emacs.orgmode/94142) on the org-mode mailing list.

- With Baikal, I get the error "The URL ... does not seem to accept DAV requests", as described in issue #30, except that `org-caldav-sync` throws the same error even on repeated attempts. The function `url-dav-supported-p` returns `nil` for all of the entry points to the Bailkal server.

Both servers are working fine with the Calendar app in OSX. I am using Emacs 24.4.1 on OSX, Org-mode 8.2.10, and the latest version of Org-caldav from MELPA.

**Comment by gour** [comment]
At the moment I use ownCloud, but want to move all stuff from Evolution to org-mode and possibly give up ownCloud, but wonder what are memory requirements for Baikal/radicale in comparison with OC?

**Comment by holri** [comment]
http://gregor.horvath-vienna.at/org-caldav_radicale.html

**Comment by dengste** [comment]
I've implemented a workaround to make Radicale work with Emacs <26. I also tested with Baikal and it worked, at least when using 'Basic' authentication. 'Digest' authentication wasn't working correctly, which is a bug in Emacs' 'url' package.

**Comment by Cumol** [comment]
I got it working with the follwing steps:

1) In the admin panel of baikal, switch from "Digest" to "Basic"
2) in org-caldav, used the following url:
https://<pathtobaikalserver>/cal.php/calendars/<username>/
<pathtobaikalserver> was in my case website.whatever/baikal/html/
3) Set up an .authinfo file with the following line:
machine website.whatever:443 port https login username password secret
Important, it does not seem to work with an .authinfo.gpg file, for whatever reason

The information were all there, but spread around. And the usualy assumption that everyone is aware how caldav, emacs, and everything in between works...
