### ISSUE TITLE
Changing calendar entries in org leads to sync error org->cal

### ISSUE THREAD

**Issue by molekular** [dengste/org-caldav#254]
Archlinux 
Emacs version 28.2
Nextcloud version 24.0.7 for caldav server (hosted by all-inkl.)

If I run org-caldav-sync new entries in org or cal will be synced correctly, two-ways.

If I change something in an org-entry and run org-caldav-sync I get the following error:

== Sync errors: 

UID: 354c57a3-be49-4aca-b9cf-277be15e73a9
   Title: Event Title
   Status: error  Action: error:org->cal
   Calendar: some-calendar

org-caldav-debug shows:

Event UID 354c57a3-be49-4aca-b9cf-277be15e73a9: Org --> Cal
Getting event UID 354c57a3-be49-4aca-b9cf-277be15e73a9.
Getting event UID 354c57a3-be49-4aca-b9cf-277be15e73a9.
UID 354c57a3-be49-4aca-b9cf-277be15e73a9: Event does not have sequence number, start with 1.
Putting event UID 354c57a3-be49-4aca-b9cf-277be15e73a9.
(Try 1) Error when trying to put URL https://my-nextcloud.de/remote.php/dav/calendars/user/id/354c57a3-be49-4aca-b9cf-277be15e73a9.ics: HTTP/1.1 415 Unsupported Media Type

It worked until recently without problems. I am not sure whether it has to do with org-caldav or something outside org-caldav (like org-mode or nextcloud), but I don't konw how to find the problem. Did someone else experience this?

**Comment by molekular** [comment]
I did some more testing. 

New entries are working perfectly - org to cal, cal to org. 

But changes in entries do not work: If I edit a calendar entry in org I get the error message above. If I edit a calendar entry in cal it is not received in org.

**Comment by molekular** [comment]
Nextcloud logs show the icalendar-data from org-caldav is rejected:

Sabre\DAV\Exception\UnsupportedMediaType: This resource only supports valid iCalendar 2.0 data. Parse error: Invalid MimeDir file. expected: "END:VCALENDAR" got: "END:VEVENT"

I also tried with a new caldav-calendar via my email provider, the problem is exactly the same. Changes in the Nextcloud calendar are synced to my mobile phone and back without issues. Therefore I think it is not related to Nextcloud. 

Could this be caused by an emacs/org-mode setting handling the export to icalendar? I am not a programmer, therefore I am stuck at this place, I would appreciate any help with this. Even a hint where to look for the cause. Thanks!

**Comment by molekular** [comment]
Figured it out, I had some misconfigured - closing this issue.

**Comment by sunng87** [comment]
hello @molekular , I'm running into the exact same issue. Do you remember what configuration was wrong in your setup?
