### ISSUE TITLE
Status of this repo?

### ISSUE THREAD

**Issue by real-or-random** [dengste/org-caldav#256]
@dengste 
This seems unmaintained, but there are a few active people (@grauschnabel @dakra @Titan-C @jackkamm @whirm) producing PRs. Would it make sense to add some of these to the repo if they're willing to help? 

Or alternatively, maybe it makes sense to agree on one of the forks, and continue development there?

**Comment by dakra** [comment]
This was discussed a few times already. See https://github.com/dengste/org-caldav/issues/179 or https://github.com/dengste/org-caldav/pull/218
And in https://github.com/dengste/org-caldav/issues/234 @dengste says he doesn't have the time
and he would be open to add other maintainers to this repo.

Personally, I currently don't even use org-caldav anymore, so I would probably not be a good maintainer.

**Comment by real-or-random** [comment]
Oh thanks, I had looked for existing issue but I must have been blind. Let's continue in #234. 

I won't @mention the people I mentioned above again there because I don't want to be annoying, but I'd be great if you could comment in #234 in case you're interested in keeping this project going.
