### ISSUE TITLE
Convert Readme from md -> org

### ISSUE THREAD

**Issue by jackkamm** [dengste/org-caldav#258]
Currently the Readme is in markdown. But it would be nicer in org-mode.

Relatedly, we should improve the package Commentary: https://github.com/dengste/org-caldav/issues/220

**Comment by edgar-vincent** [comment]
I'll do this and add a PR with potential changes today.

**Comment by jackkamm** [comment]
Fixed by https://github.com/dengste/org-caldav/commit/f42fa8c4b12857a9f29b0758b0b89eea9076d048
