### ISSUE TITLE
Past events

### ISSUE THREAD

**Issue by deb75** [dengste/org-caldav#266]
Hi,

When syncing from org to external calendar (outlook), I noticed that past events are also
pushed to the external calendar.

Is there a way to prevent `org-caldav` to sync, from org to external calendars, events that are outdated
from a given number of days ? Typically, event old by one year and more are not worth syncing.

I ask this because these past events usually produces sync errors and also,
take some time to being synced, as they become numerous with time.

Regards

**Comment by jackkamm** [comment]
I think the variable `org-caldav-days-in-past` should achieve what you want. Does it work for you?

**Comment by MaxSchlueter** [comment]
I'm looking for the same functionality. I actually don't want to keep the remote calendar clean, it should contain all the events. Instead I want to only synchronize events to an org file that are not older than X. Is this possible?
