### ISSUE TITLE
can't sync anymore : Symbol’s function definition is void: twoway

### ISSUE THREAD

**Issue by dinojr** [dengste/org-caldav#271]
Since upgrading to the latest org-mode from git (Org mode version 9.7-pre (release_9.6.3-340-g47d39c), attempting to sync with my google calendars fails with the following error. I'm using the latest org-caldav (20230331.11).

```Debugger entered--Lisp error: (void-function twoway)
  twoway((twoway org->cal) #<buffer *org-caldav-debug*>)
  #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_26>()
  funcall(#<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_26>)
  (let nil (funcall '#<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_26>))
  eval((let nil (funcall '#<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_26>)))
  org-caldav-sync-calendar()
  org-caldav-sync()
  funcall-interactively(org-caldav-sync)
  command-execute(org-caldav-sync)```

**Comment by jackkamm** [comment]
That's strange, I am also on latest org-mode from git, and not experiencing any problems with twoway sync (using Nextcloud).

From the trace, it's not obvious to me which part of `org-caldav-sync-calendar` is failing. Could you please do the following and report back:

1. Set `org-caldav-debug-level` to 2 and report output in `*org-caldav-debug*`
2. Check for any relevant output in `*Messages*`
3. `M-x toggle-debug-on-error` and run `org-caldav-sync` again, hopefully it will point to the specific line that crashes.

**Comment by dinojr** [comment]
What's even stranger is that today, after a full reboot of the system, the problem has now disappeared, maybe there was some transient conflict between emacs, org and org-caldav versions. Thanks for looking into it. I'm closing it for now.
