### ISSUE TITLE
Remove Scheduled/Deadline Prefix from Event Summary

### ISSUE THREAD

**Issue by djs42012** [dengste/org-caldav#277]
Hello,

Thank you for this wonderful package. I am trying to remove the `DL:` / `S`: prefixes prepended to the summary of Google Calendar events. I tried editing the following block in `org-caldav-convert-event-or-todo--event` from:
```lisp
(when (string-match "^\\(?:\\(DL\\|S\\):\s+\\)?\\(.*\\)$" summary)
   (setq e-type (match-string 1 summary))
   (setq summary (match-string 2 summary)))
```
to:
```lisp
(when (string-match "^\\(?:\\(DL\\|S\\):\s+\\)?\\(.*\\)$" summary)
   (setq e-type summary)
   (setq summary summary))
```
by applying some override advice, but that did not produce any visible result as far as I could see. Is there a way to do this conveniently? And might this functionality be considered for a future enhancement for those who do not require prefixes in their remote calendars?

**Comment by jackkamm** [comment]
org-caldav relies on upstream ox-icalendar.el for exporting Org to iCalendar, and it is ox-icalendar.el that adds the S/DL prefix to TODOs that are exported as calendar events.

There is not a convenient way to remove that prefix, and we have no plans to implement that.

**Comment by djs42012** [comment]
Got it. Thanks for the clarification. Just to be clear, though, these are not TODOs I am exporting to gCal, just regular entries with deadlines. I do have `org-icalendar-include-todo` and `org-caldav-sync-todo` set per the readme. Is that still the expected behavior of ox-icalendar.el in this case?

**Comment by jackkamm** [comment]
Yes I think that is the expected behavior of ox-icalendar.el -- see the variables `org-icalendar-use-deadline` and `org-icalendar-use-scheduled`.

**Comment by djs42012** [comment]
Thanks so much. I'm going to close this since it seems like something I'll have to hack around ox-icalendar.el for.
