### ISSUE TITLE
Depricated google endpoint - new endpoint doesn't work

### ISSUE THREAD

**Issue by wentasah** [dengste/org-caldav#28]
Hello,

https://developers.google.com/google-apps/calendar/caldav/v2/guide says that https://www.google.com/calendar/dav endpoint is deprecated. One should use https://apidata.googleusercontent.com/caldav/v2/calid/events instead. I tried to

```
(setq org-caldav-url "https://apidata.googleusercontent.com/caldav/v2")
```

and modified the source like this:

<pre>
diff --git a/org-caldav.el b/org-caldav.el
index cccb9bf..7241a26 100644
--- a/org-caldav.el
+++ b/org-caldav.el
@@ -322,7 +322,7 @@ Are you really sure? ")))
 
 (defun org-caldav-events-url ()
   "Return URL for events."
-  (if (string-match "google\\.com" org-caldav-url)
+  (if (string-match "google\\(usercontent\\)?\\.com" org-caldav-url)
       (concat org-caldav-url "/" org-caldav-calendar-id "/events/")
     (concat org-caldav-url "/" org-caldav-calendar-id "/")))
 
</pre>

I ended up with an error:

<pre>
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p nil)
  url-http-handle-authentication(nil)
  url-http-parse-headers()
  url-http-chunked-encoding-after-change-function(415 440 25)
  url-http-wait-for-headers-change-function(1 453 452)
  url-http-generic-filter(#<process apidata.googleusercontent.com> "HTTP/1.1 401 Unauthorized
\nWWW-Authenticate: Bearer realm=\"https://www.google.com/accounts/AuthSubRequest\"
\nContent-Type: text/html; charset=UTF-8
\nDate: Tue, 24 Sep 2013 13:32:04 GMT
\nExpires: Tue, 24 Sep 2013 13:32:04 GMT
\nCache-Control: private, max-age=0
\nX-Content-Type-Options: nosniff
\nX-Frame-Options: SAMEORIGIN
\nX-XSS-Protection: 1; mode=block
\nServer: GSE
\nAlternate-Protocol: 443:quic
\nTransfer-Encoding: chunked
\n
\ne
\nLogin Required
\n0
\n
\n")
  accept-process-output(#<process apidata.googleusercontent.com>)
  #[0 "\302\303\300@!)\207" [(#<process apidata.googleusercontent.com>) inhibit-quit nil accept-process-output] 2 "\n\n(fn)"]()
  funcall(#[0 "\302\303\300@!)\207" [(#<process apidata.googleusercontent.com>) inhibit-quit nil accept-process-output] 2 "\n\n(fn)"])
  url-retrieve-synchronously("https://apidata.googleusercontent.com/caldav/v2/wentasah@gmail.com/events/")
  url-http-options("https://apidata.googleusercontent.com/caldav/v2/wentasah@gmail.com/events/")
  url-dav-supported-p("https://apidata.googleusercontent.com/caldav/v2/wentasah@gmail.com/events/")
  (if (url-dav-supported-p (org-caldav-events-url)) nil (error "The URL %s does not seem to accept DAV requests" (org-caldav-events-url)))
  org-caldav-sync()
  call-interactively(org-caldav-sync record nil)
  command-execute(org-caldav-sync record)
  execute-extended-command(nil "org-caldav-sync")
  call-interactively(execute-extended-command nil nil)
</pre>

Any idea why is that? With the old endpoint, everything works.

**Comment by d12frosted** [comment]
You are not required to create application. It's better to ask users that want to use OAuth2 to create their own applications if they wish to use new endpoint. So 5 requests per second is good enough for almost all users. 

As example, there is `org-gcal` that works with new end point.

**Comment by sje30** [comment]
Is anyone else interested in merging org-gcal functionality into org-caldav?

**Comment by dengste** [comment]
Since Google does no longer require cell phone numbers for registering a CalDAV application, I've added that functionality. Every user will still need to register its own application with Google, though (see README).
