### ISSUE TITLE
Syncing only TODOs

### ISSUE THREAD

**Issue by ploedige** [dengste/org-caldav#287]
Hey. I really love this project but I find that I only need the syncing functionality for TODOs. Is there a way to only sync those? It would prevent users like me from accidentally breaking their calendars.

**Comment by jackkamm** [comment]
org-caldav uses ox-icalendar to export your Org file, so you can set the custom variable `org-icalendar-with-timestamps` to prevent ox-icalendar from pushing non-todo events (VEVENTs) to the caldav server.

However, this is only safe to do if your remote calendar is strictly for todos (VTODO). In particular, if your calendar contains a VEVENT, then org-caldav will import it on sync; but on the next sync, if you set `org-icalendar-with-timestamps` to nil, then ox-icalendar won't export them, making org-caldav think the event was deleted, which will propagate to the remote server.

Therefore, if you go this path, I recommend to use separate calendars for events and todos. Many CalDav servers support creating event-only and todo-only calendars, including radicale and Nextcloud.

**Comment by ploedige** [comment]
Thank you. I think that is the safest route. Having a separate ToDo calendar should reduce the risk of shooting myself in the foot by misconfiguring.
