### ISSUE TITLE
Documentation improvement request

### ISSUE THREAD

**Issue by bogamol** [dengste/org-caldav#295]
Hello,

I am trying to configure org-caldav to interact with calendars that I have set up in a nextcloud instance. For some reason, it seems to not want to use the :inbox and :files directories and is using some "~/org/appointments.org" file that is hard-coded into the .el file. 

It also returns that the folder I am linked to does not accept DAV requests.

If I could better understand the documentation, e.g. what format should file paths be, or what format the org-calendar-id should be configured in, then I think I would be able to get this up and running. Right now, I've spent the better part of a day and am still coming up short.

It's also really difficult to see what other options are present and how they can be used.

Is there a way I can help with writing documentation?  

Sincerely, 

Robert

**Comment by jackkamm** [comment]
We're aware the documentation needs to improve, and this is a work in progress. I've made a first step by merging #294 today. Let us know if you have better luck with the updated docs.

**Comment by jackkamm** [comment]
Closing this (and other documentation-related issues) in favor of https://github.com/dengste/org-caldav/issues/296
