### ISSUE TITLE
Fresh sync on TODO/task

### ISSUE THREAD

**Issue by ratsclub** [dengste/org-caldav#297]
Currently, running `org-caldav-sync` for the first time on a *tasks-only calendar* doesn't create the `.org` file with the current tasks. It asks me if I want to delete the entries already there instead of "exporting" the entries to the file.

How can I make the fresh sync get all the task entries?

**Comment by ratsclub** [comment]
The workaround I found was to set `org-caldav-sync-direction` to `'cal->org` and then setting it back to `twoway`.

**Comment by jackkamm** [comment]
I cannot reproduce this. Can you provide more details about your config and the steps you took? Also, are you able to reproduce this with a fresh icalendar and minimal init.el?

Here's what I did:

1. Create a new tasks calendar via Nextcloud Tasks tab, and add a few tasks

2. Run `emacs -q --load init.el`, here's relevant part of `init.el`:
```
(setq org-caldav-url "REDACTED")
(setq org-caldav-calendar-id "REDACTED")

(setq org-caldav-inbox "/path/to/test.org")
(setq org-caldav-files nil)

(setq org-caldav-sync-todo t)
(setq org-icalendar-include-todo 'all)
(setq org-caldav-sync-changes-to-org 'all)

(setq org-caldav-backup-file "/path/to/backup-file.org")
(setq org-caldav-debug-level 2)
(toggle-debug-on-error 1)
(require 'org-caldav)
```

3. `M-x org-caldav-sync`

Then, org-caldav successfully created and populated `test.org`

**Comment by ratsclub** [comment]
I replaced my entire configuration with the one provider here and it worked just fine. Thank you so much!
