### ISSUE TITLE
Syncing Error: Could not find UID...

### ISSUE THREAD

**Issue by mourningsun75** [dengste/org-caldav#32]
Hi,

because of this error i switched from owncloud to baikal. But the error stays the same....

Every sync aborts with the message:
Could not find UID TS10-aa7e8257-c44f-47ef-b8ac-eb72130b8156.

The Message Buffer says:
Duplicate ID "29b80a9d-597d-459e-bea5-f5f671b59ea5", also in file
.....
.....
....
WARNING: 28 duplicate IDs found, check *Messages* buffer
progn: Could not find UID TS10-aa7e8257-c44f-47ef-b8ac-eb72130b8156.

I have also run "C-u M-x org-caldav-delete-everything" but it changed nothing. :-(

How can i solve this error?

**Comment by dengste** [comment]
OK, closing...
