### ISSUE TITLE
url-http-options: Selecting deleted buffer when trying to sync with baikal

### ISSUE THREAD

**Issue by mourningsun75** [dengste/org-caldav#50]
The sync with owncloud works perfect. 

When i try to sync with my baikal installation i only get the following error:
url-http-options: Selecting deleted buffer

URL and Account Data is set correctly.

**Comment by mourningsun75** [comment]
Nobody can help?

**Comment by dengste** [comment]
I just tested with Baikal and it worked when using 'Basic' authentication. 'Digest' authentication will usually not work, which is a bug in Emacs' 'url' package.
