### ISSUE TITLE
>1 calendars not working after 24.4, syncs same items to both

### ISSUE THREAD

**Issue by unhammer** [dengste/org-caldav#51]
I have

```
(setq org-caldav-calendars
  '((:calendar-id "org-work"
          :agenda-skip-function (org-agenda-skip-work 'inverse)
              :inbox "~/Dokument/org/caldav-inbox-work.org")
    (:calendar-id "org-home"
          :agenda-skip-function org-agenda-skip-work
              :inbox "~/Dokument/org/caldav-inbox-home.org")))
```

which worked great with emacs 24.3, but after 24.4, the upgraded org-mode first started adding PROPERTIES to all entries (regardless of whether they had dates and were to be exported or not), and then org-caldav started putting all my work stuff in my home calendar (saying things like "putting event 1 of 288" which is an obvious hint that things are not working :)).

However, within the regular agenda, the skip commands work fine, so something must not be communicated to the exporter.

**Comment by gour** [comment]
> the upgraded org-mode first started adding PROPERTIES to all entries (regardless of whether they had dates and were to be exported or not), and then org-caldav started putting all my work stuff in my home calendar 

Just migrated back to Emacs/org-mode and experiencing the same thing. :disappointed: 

Is there any workaround for those using >1 calendar?

**Comment by unhammer** [comment]
I stopped using org-caldav due to this issue, so I don't know.

**Comment by gour** [comment]
> I stopped using org-caldav due to this issue, so I don't know.

Any suggestion what to use with org-mode?

For contacts I use Damien's [vdirel](https://github.com/DamienCassou/vdirel) along with [khard](https://github.com/scheibler/khard/), so one possibility is to use [khal](https://github.com/pimutils/khal) to create entries, then to convert *.ics created by [vdirsyncer](https://github.com/pimutils/vdirsyncer) to org and finally import into org-mode, but it's not 2-way sync. :cry:

Any (other) suggestion?

**Comment by dengste** [comment]
The old icalendar exporter used the agenda commands, so the org-agenda-skip-function worked as expected. The new exporter does not do this, and there's no easy way to get this back. You can however put a filtering function into the org-export-before-parsing-hook. Since that is not really straightforward to do, I implemented this in org-caldav in the form of the new variable org-caldav-skip-conditions.
