### ISSUE TITLE
A problem when running sync in MS windows

### ISSUE THREAD

**Issue by yangguang760** [dengste/org-caldav#55]
I've tried to run the org-calDAV-sync under MS windows (8.1, 64-bit), the error messages are as follows.

open-network-stream: make client process failed: connection timed out, :name, www.google.com, :buffer, #<killed buffer>, :host, www.google.com, :service, 443, :nowait, nil

any suggestions? thx

**Comment by dengste** [comment]
My guess would be your Emacs does not have GnuTLS support.
