### ISSUE TITLE
Caldav-Sync-Problem: No UID could be found for current event.

### ISSUE THREAD

**Issue by stvharman** [dengste/org-caldav#58]
When I issue M-x org-caldav-sync, it stops after putting four events on my owncloud calendar and I get the error given at the bottom: 

Any help would be greatly appreciated.

thanks

Error log
-----------

Debugger entered--Lisp error: (error "No UID could be found for current event.")
  signal(error ("No UID could be found for current event."))
  error("No UID could be found for current event.")
  (if (re-search-forward "^UID:\\s-*\\(.+\\)\\s-*$" nil t) (let ((uid (match-string 1))) (while (progn (forward-line) (looking-at " \\(.+\\)\\s-*$")) (setq uid (concat uid (match-string 1)))) (while (string-match "\\s-+" uid) (setq uid (replace-match "" nil nil uid))) (if (string-match "^\\([A-Z][A-Z][0-9]*-\\)" uid) (progn (setq uid (replace-match "" nil nil uid)))) uid) (error "No UID could be found for current event."))
  org-caldav-get-uid()
  (setq uid (org-caldav-get-uid))
  (and (setq uid (org-caldav-get-uid)) (not (string-match (car cur) uid)))
  (while (and (setq uid (org-caldav-get-uid)) (not (string-match (car cur) uid))))
  (if (eq (org-caldav-event-etag cur) (quote put)) (org-caldav-debug-print 1 (format "Event UID %s: Was already put previously." (car cur))) (org-caldav-debug-print 1 (format "Event UID %s: Org --> Cal" (car cur))) (widen) (goto-char (point-min)) (while (and (setq uid (org-caldav-get-uid)) (not (string-match (car cur) uid)))) (if (string-match (car cur) uid) nil (error "Could not find UID %s" (car cur))) (org-caldav-narrow-event-under-point) (org-caldav-cleanup-ics-description) (org-caldav-maybe-fix-timezone) (org-caldav-set-sequence-number cur event-etag) (message "Putting event %d of %d" counter (length events)) (if (org-caldav-put-event icsbuf) (org-caldav-event-set-etag cur (quote put)) (org-caldav-debug-print 1 (format "Event UID %s: Error while doing Org --> Cal" (car cur))) (org-caldav-event-set-status cur (quote error)) (setq org-caldav-sync-result (cons (list org-caldav-calendar-id (car cur) (quote error) (quote error:org->cal)) org-caldav-sync-result))))
  (while --dolist-tail-- (setq cur (car --dolist-tail--)) (setq counter (1+ counter)) (if (eq (org-caldav-event-etag cur) (quote put)) (org-caldav-debug-print 1 (format "Event UID %s: Was already put previously." (car cur))) (org-caldav-debug-print 1 (format "Event UID %s: Org --> Cal" (car cur))) (widen) (goto-char (point-min)) (while (and (setq uid (org-caldav-get-uid)) (not (string-match (car cur) uid)))) (if (string-match (car cur) uid) nil (error "Could not find UID %s" (car cur))) (org-caldav-narrow-event-under-point) (org-caldav-cleanup-ics-description) (org-caldav-maybe-fix-timezone) (org-caldav-set-sequence-number cur event-etag) (message "Putting event %d of %d" counter (length events)) (if (org-caldav-put-event icsbuf) (org-caldav-event-set-etag cur (quote put)) (org-caldav-debug-print 1 (format "Event UID %s: Error while doing Org --> Cal" (car cur))) (org-caldav-event-set-status cur (quote error)) (setq org-caldav-sync-result (cons (list org-caldav-calendar-id (car cur) (quote error) (quote error:org->cal)) org-caldav-sync-result)))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- events) cur) (while --dolist-tail-- (setq cur (car --dolist-tail--)) (setq counter (1+ counter)) (if (eq (org-caldav-event-etag cur) (quote put)) (org-caldav-debug-print 1 (format "Event UID %s: Was already put previously." (car cur))) (org-caldav-debug-print 1 (format "Event UID %s: Org --> Cal" (car cur))) (widen) (goto-char (point-min)) (while (and (setq uid (org-caldav-get-uid)) (not (string-match (car cur) uid)))) (if (string-match (car cur) uid) nil (error "Could not find UID %s" (car cur))) (org-caldav-narrow-event-under-point) (org-caldav-cleanup-ics-description) (org-caldav-maybe-fix-timezone) (org-caldav-set-sequence-number cur event-etag) (message "Putting event %d of %d" counter (length events)) (if (org-caldav-put-event icsbuf) (org-caldav-event-set-etag cur (quote put)) (org-caldav-debug-print 1 (format "Event UID %s: Error while doing Org --> Cal" (car cur))) (org-caldav-event-set-status cur (quote error)) (setq org-caldav-sync-result (cons (list org-caldav-calendar-id (car cur) (quote error) (quote error:org->cal)) org-caldav-sync-result)))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((events (append (org-caldav-filter-events (quote new-in-org)) (org-caldav-filter-events (quote changed-in-org)))) (counter 0) (url-show-status nil) (event-etag (org-caldav-get-event-etag-list)) uid) (let ((--dolist-tail-- events) cur) (while --dolist-tail-- (setq cur (car --dolist-tail--)) (setq counter (1+ counter)) (if (eq (org-caldav-event-etag cur) (quote put)) (org-caldav-debug-print 1 (format "Event UID %s: Was already put previously." (car cur))) (org-caldav-debug-print 1 (format "Event UID %s: Org --> Cal" (car cur))) (widen) (goto-char (point-min)) (while (and (setq uid (org-caldav-get-uid)) (not (string-match ... uid)))) (if (string-match (car cur) uid) nil (error "Could not find UID %s" (car cur))) (org-caldav-narrow-event-under-point) (org-caldav-cleanup-ics-description) (org-caldav-maybe-fix-timezone) (org-caldav-set-sequence-number cur event-etag) (message "Putting event %d of %d" counter (length events)) (if (org-caldav-put-event icsbuf) (org-caldav-event-set-etag cur (quote put)) (org-caldav-debug-print 1 (format "Event UID %s: Error while doing Org --> Cal" (car cur))) (org-caldav-event-set-status cur (quote error)) (setq org-caldav-sync-result (cons (list org-caldav-calendar-id ... ... ...) org-caldav-sync-result)))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (setq event-etag (org-caldav-get-event-etag-list)) (let ((--dolist-tail-- events) cur) (while --dolist-tail-- (setq cur (car --dolist-tail--)) (let ((etag (assoc (car cur) event-etag))) (if (and (not (eq ... ...)) etag) (progn (org-caldav-event-set-etag cur (cdr etag)) (setq org-caldav-sync-result (cons ... org-caldav-sync-result))))) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  (save-current-buffer (set-buffer icsbuf) (widen) (goto-char (point-min)) (let ((events (append (org-caldav-filter-events (quote new-in-org)) (org-caldav-filter-events (quote changed-in-org)))) (counter 0) (url-show-status nil) (event-etag (org-caldav-get-event-etag-list)) uid) (let ((--dolist-tail-- events) cur) (while --dolist-tail-- (setq cur (car --dolist-tail--)) (setq counter (1+ counter)) (if (eq (org-caldav-event-etag cur) (quote put)) (org-caldav-debug-print 1 (format "Event UID %s: Was already put previously." (car cur))) (org-caldav-debug-print 1 (format "Event UID %s: Org --> Cal" (car cur))) (widen) (goto-char (point-min)) (while (and (setq uid ...) (not ...))) (if (string-match (car cur) uid) nil (error "Could not find UID %s" (car cur))) (org-caldav-narrow-event-under-point) (org-caldav-cleanup-ics-description) (org-caldav-maybe-fix-timezone) (org-caldav-set-sequence-number cur event-etag) (message "Putting event %d of %d" counter (length events)) (if (org-caldav-put-event icsbuf) (org-caldav-event-set-etag cur (quote put)) (org-caldav-debug-print 1 (format "Event UID %s: Error while doing Org --> Cal" ...)) (org-caldav-event-set-status cur (quote error)) (setq org-caldav-sync-result (cons ... org-caldav-sync-result)))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (setq event-etag (org-caldav-get-event-etag-list)) (let ((--dolist-tail-- events) cur) (while --dolist-tail-- (setq cur (car --dolist-tail--)) (let ((etag (assoc ... event-etag))) (if (and (not ...) etag) (progn (org-caldav-event-set-etag cur ...) (setq org-caldav-sync-result ...)))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (let ((events (org-caldav-filter-events (quote deleted-in-org))) (url-show-status nil) (counter 0)) (let ((--dolist-tail-- events) cur) (while --dolist-tail-- (setq cur (car --dolist-tail--)) (setq counter (1+ counter)) (message "Deleting event %d from %d" counter (length events)) (org-caldav-delete-event (car cur)) (setq org-caldav-sync-result (cons (list org-caldav-calendar-id (car cur) (quote deleted-in-org) (quote removed-from-cal)) org-caldav-sync-result)) (setq org-caldav-event-list (delete cur org-caldav-event-list)) (setq --dolist-tail-- (cdr --dolist-tail--))))) (let ((--dolist-tail-- (org-caldav-filter-events (quote error))) cur) (while --dolist-tail-- (setq cur (car --dolist-tail--)) (setq org-caldav-event-list (delete cur org-caldav-event-list)) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  org-caldav-update-events-in-cal(#<buffer org-caldav-25267wC2>)
  (let ((org-caldav-url org-caldav-url) (org-caldav-calendar-id org-caldav-calendar-id) (org-caldav-files org-caldav-files) (org-caldav-select-tags org-caldav-select-tags) (org-caldav-inbox org-caldav-inbox) (org-caldav-empty-calendar nil)) (while calendar (let ((key (car-safe (prog1 calendar (setq calendar ...)))) (value (car-safe (prog1 calendar (setq calendar ...))))) (set (org-caldav-var-for-key key) value))) (org-caldav-check-connection) (if resume nil (setq org-caldav-ics-buffer (org-caldav-generate-ics)) (setq org-caldav-event-list nil) (org-caldav-load-sync-state) (let ((--dolist-tail-- org-caldav-event-list) cur) (while --dolist-tail-- (setq cur (car --dolist-tail--)) (org-caldav-event-set-status cur nil) (setq --dolist-tail-- (cdr --dolist-tail--)))) (org-caldav-update-eventdb-from-org org-caldav-ics-buffer) (org-caldav-update-eventdb-from-cal)) (org-caldav-update-events-in-cal org-caldav-ics-buffer) (org-caldav-update-events-in-org) (org-caldav-save-sync-state) (setq org-caldav-event-list nil) (save-current-buffer (set-buffer org-caldav-ics-buffer) (set-buffer-modified-p nil) (kill-buffer)) (delete-file (buffer-file-name org-caldav-ics-buffer)))
  org-caldav-sync-calendar()
  (if (null org-caldav-calendars) (org-caldav-sync-calendar) (let ((--dolist-tail-- org-caldav-calendars) calendar) (while --dolist-tail-- (setq calendar (car --dolist-tail--)) (org-caldav-debug-print 1 "Syncing first calendar entry:" calendar) (org-caldav-sync-calendar calendar) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  (if (and org-caldav-event-list (y-or-n-p "Last sync seems to have been aborted. Should I try to resume? ")) (org-caldav-sync-calendar org-caldav-previous-calendar t) (setq org-caldav-sync-result nil) (if (null org-caldav-calendars) (org-caldav-sync-calendar) (let ((--dolist-tail-- org-caldav-calendars) calendar) (while --dolist-tail-- (setq calendar (car --dolist-tail--)) (org-caldav-debug-print 1 "Syncing first calendar entry:" calendar) (org-caldav-sync-calendar calendar) (setq --dolist-tail-- (cdr --dolist-tail--))))))
  org-caldav-sync()
  call-interactively(org-caldav-sync record nil)
  command-execute(org-caldav-sync record)
  execute-extended-command(nil "org-caldav-sync")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

**Comment by dtbaumann** [comment]
I can confirm this error:
As far as I found out this occurs during the first sync of a calendar.
If more than one org-file is synced this error occurs with the last entry with a timestamp in the last file to be synced. Reordering the org-files throws an error at a different, but again at the last uid. Therefore I am certain that all entries are syntactically correct.

I checked the uid which was said to be causing the problem and it is present in the org-file and in the generated ics calendar.

After several hour of debugging I'm currently back to a version from long ago, although I would like to make use of the multiple calendar feature.

Thanks for looking into this
Thomas

**Comment by mirren** [comment]
Same here. It stops after generating the "No UID could be found for current event." error message. I am synchronizing for the first time. Resetting the calendar and org file resulted in hanging at a different UID though. 
Which is the version that does not have this issue?

**Comment by mirren** [comment]
well, at least for me the problem was I had mixed IDs (some from org-mobile with low case letters) which seemed to confuse org-caldav. After deleting all IDS and rebuilding the calendar a couple of times it works pretty smoothly now.
