### ISSUE TITLE
Prevent new buffer opening after running org-caldav-sync

### ISSUE THREAD

**Issue by stvharman** [dengste/org-caldav#64]
When I run the sync, it opens a new buffer with the following:

  CalDAV Sync finished.
  
  Nothing was done.

While it may not seem important when the sync is run manually, when it comes to running it automatically, it is preferrable to avoid a new buffer and use either a log file or simply run in a silent mode. 

I was wondering if there is any way to prevent a new buffer opening. Thanks

**Comment by monoverse** [comment]
There is a variable _org-caldav-show-sync-results_. Set it to _nil_ and you are done.
