### ISSUE TITLE
trying to sync with google calendar

### ISSUE THREAD

**Issue by gekoc** [dengste/org-caldav#65]
I just tried org-caldav with the following setting:
------------------------------------------------
(require 'org-caldav)
(setq org-caldav-url "https://www.google.com/calendar/dav")
(setq org-caldav-calendar-id "my.self@gmail.com")
(setq org-caldav-inbox "~/org/calendar.org")
(setq org-caldav-files "~/org/notes.org")

--------------------------------------------------

but I keep ending with the following backtrace:
-----------------------------------------------------------------
Debugger entered--Lisp error: (wrong-type-argument stringp 126)
  file-exists-p(126)
  org-check-agenda-file(126)
  byte-code(........)
  org-agenda-prepare-buffers((126 47 111 114 103 97 110 105 122 101 114 47 115 111 117 114 99 101 47 114 105 115 113 117 101 115 80 115 121 99 104 111 83 111 99 105 97 117 120 46 111 114 103  "~/org/calendar.org"))
  org-icalendar--combine-files(nil 126 47 111 114 103 97 110 105 122 101 114 47 115 111 117 114 99 101 47 114 105 115 113 117 101 115 80 115 121 99 104 111 83 111 99 105 97 117 120 46 111 114 103  "~/org/calendar.org")
  apply(org-icalendar--combine-files nil (126 47 111 114 103 97 110 105 122 101 114 47 115 111 117 114 99 101 47 114 105 115 113 117 101 115 80 115 121 99 104 111 83 111 99 105 97 117 120 46 111 114 103 "~/org/calendar.org"))
  org-caldav-generate-ics()
  org-caldav-sync-calendar()
  org-caldav-sync()
  call-interactively(org-caldav-sync record nil)
  command-execute(org-caldav-sync record)
  execute-extended-command(nil "org-caldav-sync")

------------------------------------------------------------------------

Any idea about what's going wrong?

--

**Comment by V155** [comment]
Yes. org-caldav-files expects a list and not a string.

    (setq org-caldav-files '("~/org/notes.org"))

this should solve your problem

**Comment by gekoc** [comment]
Thanks.
Things are now working with one of my google accounts but with my other account I run into some errors.  How is that possible?

*org-caldav-debug*
-----------------------------------------------------------------------------
========== Started sync.
Check connection for https://www.google.com/calendar/dav/firstName.lastName@gmail.com/events/.
Got error status from PROPFIND: 
(("https://www.google.com/calendar/dav/firstName.lastName@gmail.com/events/" DAV:status 404 . ""))
----------------------------------------------------------------------------

*Backtrace*
-----------------------------------------------------------------------
Debugger entered--Lisp error: (error "Could not query CalDAV URL https://www.google.com/calendar/dav/firstName.lastName@gmail.com/events/.")
  signal(error ("Could not query CalDAV URL https://www.google.com/calendar/dav/firstName.lastName@gmail.com/events/."))
  error("Could not query CalDAV URL %s." "https://www.google.com/calendar/dav/jeanluc.koning@gmail.com/events/")
  org-caldav-check-connection()
  org-caldav-sync-calendar()
  org-caldav-sync()
  call-interactively(org-caldav-sync record nil)
  command-execute(org-caldav-sync record)
  execute-extended-command(nil "org-caldav-sync")
------------------------------------------------------------------------

**Comment by gekoc** [comment]
Apparently, my problem seems to be coming from .authinfo.gpg
When I delete it then it's working alright.

I need to fix it but I don't know where to look for as everything in there looks ok.

**Comment by gekoc** [comment]
The reason was, I had 2 such lines in .authinfo.gpg with 2 different usernames:

  machine www.google.com:443 port https login USERNAME password PASS

The second line was not taken into account.
