### ISSUE TITLE
Code to convert ICS file to event in org mode

### ISSUE THREAD

**Issue by DamienCassou** [dengste/org-caldav#69]
Thanks to your code, I wrote the following code to convert an `.ics` file (e.g., received as attachment to an email) to an org event in the `org-caldav-inbox`:

```lisp
(defun my:import-ics-to-org (path)
      (with-current-buffer (get-buffer-create "*import-ics-to-org*")
        (delete-region (point-min) (point-max))
        (insert-file-contents path)
        (let ((event (org-caldav-convert-event)))
          (with-current-buffer (find-file-noselect (org-caldav-inbox-file org-caldav-inbox))
            (let* ((point-and-level (org-caldav-inbox-point-and-level org-caldav-inbox))
                   (point (car point-and-level))
                   (level (cdr point-and-level)))
              (goto-char point)
              (apply #'org-caldav-insert-org-entry
                     (append event (list nil level))))))))
```

This depends on #67 being merged. Would it make sense to include this in `org-caldav`?

**Comment by DamienCassou** [comment]
I improved this, is anyone interested?

**Comment by dengste** [comment]
I rather not include it in org-caldav, as I really want to restrict it to syncing as much as possible. Dealing with calendar attachments is work for another package. Personally, I use gnus-icalendar for this.
