### ISSUE TITLE
sync error after updating to org 8.3.1

### ISSUE THREAD

**Issue by mourningsun75** [dengste/org-caldav#75]
After the update to org 8.3.1 i get the following error when i try to sync my calender:

Wrong type argument: listp, #("XXX YYY" 0 11 (:parent (#0)))

Debugger entered--Lisp error: (wrong-type-argument listp #("XXX YYY" 0 11 (:parent (#1))))
  org-element-set-contents(#("XXX YYY" 0 11 (:parent (#0))))
  apply(org-element-set-contents #("XXX YYY" 0 11 (:parent (#0))) nil)
  #[(s) "^H\306\307\310^H#^Y^Z\311\312  \211^[:\204^U^@\313\202\"^@^K@9\203!^@^KAA\202\"^@^K)\"\210\314\315\n   \211^[:\2043^@\313\202@^@^K@9\203?^@^KAA\202@^@^K)#\210 \316\211\n^[^^K;\20$
  #[(--data) "^H\211^Y:\204^P^@ ;\205^X^@\306\202^X^@   @9\205^X^@      @)^Z^H?\206\337^A^K\203,^@^H\307^K\310\">\206\337^A\n\2047^@\311\f^H\"\202\337^A\n\312=\203\^@\311\f^H\211^Y:\204J^$
  mapc(#[(--data) "^H\211^Y:\204^P^@    ;\205^X^@\306\202^X^@   @9\205^X^@      @)^Z^H?\206\337^A^K\203,^@^H\307^K\310\">\206\337^A\n\2047^@\311\f^H\"\202\337^A\n\312=\203\^@\311\f^H\211^$
  #[(--data) "^H\211^Y:\204^P^@ ;\205^X^@\306\202^X^@   @9\205^X^@      @)^Z^H?\206\337^A^K\203,^@^H\307^K\310\">\206\337^A\n\2047^@\311\f^H\"\202\337^A\n\312=\203\^@\311\f^H\211^Y:\204J^$
  byte-code("^H !\210\n\237\207" [--walk-tree data --acc] 2)
  org-element-map((#("XXX YYY" 0 11 (:parent #0))) plain-text #[(s) "^H\306\307\310^H#^Y^Z\311\312  \211^[:\204^U^@\313\202\"^@^K@9\203!^@^KAA\202\"^@^K)\"\210\314\315\n   \211^[:\2043$
  org-export--get-inbuffer-options([cl-struct-org-export-backend icalendar ascii ((clock . ignore) (footnote-definition . ignore) (footnote-reference . ignore) (headline . org-icalendar-en$
  org-export-get-environment([cl-struct-org-export-backend icalendar ascii ((clock . ignore) (footnote-definition . ignore) (footnote-reference . ignore) (headline . org-icalendar-entry) ($
  org-export-as(icalendar nil nil t (:ascii-charset utf-8 :ascii-links-to-notes nil))
  byte-code("\302^H!\210r\303^H!q\210   \203^S^@\304^H\305\"\210\306\307\310\211\305\311%)\207" [file org-icalendar-store-UID org-check-agenda-file org-get-agenda-file-buffer org-icalendar$
  #[(file) "\300\301\215\207" [nextfile (byte-code "\302^H!\210r\303^H!q\210    \203^S^@\304^H\305\"\210\306\307\310\211\305\311%)\207" [file org-icalendar-store-UID org-check-agenda-file $
  mapconcat(#[(file) "\300\301\215\207" [nextfile (byte-code "\302^H!\210r\303^H!q\210  \203^S^@\304^H\305\"\210\306\307\310\211\305\311%)\207" [file org-icalendar-store-UID org-check-agen$
  org-icalendar--combine-files("~/org/orgfiles/file1.org" "~/org/orgfiles/file2.org" "~/org/orgfiles/file3.org")
  apply(org-icalendar--combine-files ("~/org/orgfiles/termine.org" "~/org/orgfiles/tage.org" "~/org/orgfiles/inbox.org"))
  org-caldav-generate-ics()
  org-caldav-sync-calendar()
  org-caldav-sync()
  cal-sync()
  call-interactively(cal-sync nil nil)
  command-execute(cal-sync)

When i call C-u m-x org-reload before the sync it works....

**Comment by uMtMu** [comment]
I got this error "Wrong type argument: listp, #("XXX" 0 11 (:parent (#0)))" when i try to export org file. My version is "20160229"

**Comment by dengste** [comment]
This should be fixed
