### ISSUE TITLE
Automatically adding reminders (Please add to README)

### ISSUE THREAD

**Issue by mgagliol** [dengste/org-caldav#77]
I think this may be useful to others: setting `org-icalendar-alarm-time` to a nonzero value N adds a reminder N minutes before timestamp, eg:
```lisp
(setq org-icalendar-alarm-time 60)
```
adds a reminder 1 hour before the event timestamp. Maybe add this to README?

Thanks a lot for a very useful piece of code :)

**Comment by dengste** [comment]
Thanks, I did not know that! I mentioned it in the Readme.
