### ISSUE TITLE
Can I have a TODO calendar?

### ISSUE THREAD

**Issue by grauschnabel** [dengste/org-caldav#85]
Hi there,

I would like to create a new google calendar for todo items with SCHEDULED or DEADLINE entries.  But I have a gtd.org file which holds a Calendar and a Tasks headlines where my Calendar is synced great, todos are ignored at the moment.  (And other calendars in other files using the multple calendar config)

Can I change my configuration to put the TODOs into a different google calendar?

thanks,
Martin

**Comment by olberger** [comment]
AFAIU, this is pretty much the same as #33

**Comment by dengste** [comment]
Yes, use the org-icalendar-use-deadline/scheduled variables for this.
