### ISSUE TITLE
Can we add an option to supress the resume prompt?

### ISSUE THREAD

**Issue by ddoherty03** [dengste/org-caldav#87]
dengste, I'm successfully using org-caldav with an owncloud server, so I can get my appointments to show up on my iPhone reliably.  So many thanks.

When I sync, I consistently get errors like
 "Could not find UID owncloud-7385ef2a9c6fc2b9d5db725a39ccb746."

When I sync again, all is well, except that it prompts me about whether I want to resume.  Because I run the sync on a timer in the background, this means I have to manually run the sync.  So over a weekend, I come into the office with several such prompts blocking emacs.

I would love to have a custom variable that I set to always resume a failed sync.  Is this feasible?

Thanks.

**Comment by ddoherty03** [comment]
By the way, I notice that I never said "thanks" for implementing this fix.  I am truly grateful, so many thanks, @dengste.

**Comment by grauschnabel** [comment]
Thats very interesting to me, that you say, you run out in the background with a timer. Could you please show me your settings for that? For me, I didn't get it to run in the background, so please...

**Comment by ddoherty03** [comment]
@grauschnabel, here is the relevant portion of my init file:
Only on micah, run this every 12 hours (= 42200 seconds).

```elisp
  (if (string-match "^micah" (system-name))
             (setq ded-caldav-timer (run-at-time t 42200 'ded-org-caldav-sync)))
```
The function, ded-org-caldav-sync just sets all my sync-related variables, then invokes org-caldav-sync.  I assign the timer returned by run-at-time to a variable so I can stop it if need be.

I hope that helps.
