### ISSUE TITLE
Support SCHEDULED and DEADLINE properties

### ISSUE THREAD

**Issue by meiyopeng** [dengste/org-caldav#88]
Org-caldav does not recognize SCHEDULED and DEADLINE properties in org entries.
```
* Do something
  DEADLINE: <2016-05-19 Thu> SCHEDULED: <2016-05-18 Wed>
```
I have to manually add a time stamp `<2016-05-18 Wed>` in the body so that org-caldav will sync this entry. 
```
* Do something
  DEADLINE: <2016-05-19 Thu> SCHEDULED: <2016-05-18 Wed>
  <2016-05-18 Wed>
```
This is redundant. Why not support SCHEDULED property?

**Comment by minkkinen** [comment]
I haven't used org-caldav for a while so can't test right now, but I think you need to look into the variables `org-icalendar-use-deadline` and `org-icalendar-use-scheduled` and possibly also `org-icalendar-include-todo` and `org-icalendar-with-timestamps`. 
Check here for a similar question: #33

**Comment by meiyopeng** [comment]
I executed the following code in Emacs. It works. Scheduled events were synced to Google Calender.
```
(setq org-icalendar-use-deadline '(event-if-todo event-if-not-todo todo-due)
      org-icalendar-use-scheduled '(event-if-todo event-if-not-todo todo-start))
```
@minkkinen Thank you. I'm going to close this issue.
