### ISSUE TITLE
Problem while syncing with nextcloud (fork of owncloud)

### ISSUE THREAD

**Issue by mourningsun75** [dengste/org-caldav#90]
I want to switch to the owncloud fork nextcloud. but when i try to sync i get the following error:

```
 error in process filter: Invalid date: 31-Dec-2100 23:59:59.00 GMT

  Debugger entered--Lisp error: (error "Invalid date: 31-Dec-2100 23:59:59.00 GMT")
  signal(error ("Invalid date: 31-Dec-2100 23:59:59.00 GMT"))
  error("Invalid date: %s" "31-Dec-2100 23:59:59.00 GMT")
  byte-code("\300\301\302\217\207" [nil (byte-code "\301\302\303\304^H!!\"\207" [date apply encode-time parse-time-string timezone-make-date-arpa-standard] 5) ((error (error "Invalid date:$
  date-to-time("31-Dec-2100 23:59:59.00 GMT")
  url-cookie-expired-p([url-cookie "nc_sameSiteCookiestrict" "true" "31-Dec-2100 23:59:59.00 GMT" "/" "my_url" t])
  url-cookie-retrieve("myurl" "/remote.php/dav/calendars/user/orgmode/" t)
  url-cookie-generate-header-lines("myurl" "/remote.php/dav/calendars/user/orgmode/" t)
  url-http-create-request()
  url-http([cl-struct-url "https" nil nil "myurl" nil "/remote.php/dav/calendars/user/orgmode/" nil nil t nil t] #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207"$
  url-https([cl-struct-url "https" nil nil "myurl" nil "/remote.php/dav/calendars/user/orgmode/" nil nil t nil t] #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207$
  url-retrieve-internal("https://myurl/remote.php/dav/calendars/user/orgmode/" #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval $
  url-retrieve("https://myurl/remote.php/dav/calendars/user/orgmode/" #[128 " \302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchron$
  url-retrieve-synchronously("https://myurl/remote.php/dav/calendars/user/orgmode/")
  url-http-options("https://myurl/remote.php/dav/calendars/user/orgmode/")
  url-dav-supported-p("https://myurl/remote.php/dav/calendars/user/orgmode/")
  org-caldav-check-connection()
  org-caldav-sync-calendar()
  org-caldav-sync()
  cal-sync()
  call-interactively(cal-sync nil nil)
  command-execute(cal-sync)

```

I know that the nextcloud devs changes something with cookies in the first release.

When i call url-cookie-list there are differences between the owncloud and nextcloud cookies:

nextcloud

```
  myurl SameSite          strict
                 httponly             nil
                 nc_sameSiteCookielax true
                 nc_sameSiteCookiestr true
                 oc_sessionPassphrase blablbla
   myurl HttpOnly          nil

```

owncloud

```
   myurl HttpOnly          nil
                 httponly             nil
                 oc_sessionPassphrase blablbalb
myurl HttpOnly          nil

```

Org-mode version 8.3.4
GNU Emacs 24.4.1

Somebody else have this problem?
What is to do?

**Comment by mourningsun75** [comment]
Nobody has the problem or nobody uses nextcloud?

**Comment by mourningsun75** [comment]
Has someone a working setup with nextcloud and org-caldav?

**Comment by mourningsun75** [comment]
I think here is the solution:
https://help.nextcloud.com/t/davdroid-no-longer-works-with-nc/579/39

It will not work until org-caldav will fix it....

**Comment by drym3r** [comment]
It also happens to me, which is weird since I could sync a couple of times after upgrading to nextcloud.

**Comment by mourningsun75** [comment]
Nothing New?

**Comment by hrehfeld** [comment]
FYI, I have a working nextcloud sync, no problems yet.

**Comment by dengste** [comment]
I successfully synced with Nextcloud 11.0.3 and Emacs 25.2., so I cannot reproduce this.

**Comment by mvsjober** [comment]
I just tried it again on Emacs 24.5.1 and Nextcloud 11.03, and I'm getting "does not seem to accept DAV requests". Perhaps it's something about the older Emacs version?

**Comment by hrehfeld** [comment]
I'm getting the same, but *only on the first sync* with `GNU Emacs 25.2.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.22.10) of 2017-04-22`

**Comment by dengste** [comment]
OK, but to clear, you are both **not** getting the above "invalid date" error, right? Simply that the URL does not accept DAV requests?

**Comment by dengste** [comment]
Please try again with latest org-caldav which is more verbose as to where exactly the check for DAV is failing.

**Comment by mvsjober** [comment]
@dengste Correct, I'm not seeing the "invalid date" error. Maybe this is the wrong issue thread then?

I upgraded to org-caldav version 20170517.1157. Doesn't work, but has a more detailed error message. BTW, it doesn't even get to the part where it asks for my password. This is what I see in `*Messages*` (I've replaced my real hostname with a dummy below.)

```
Contacting host: my.nextcloud.tld:443
org-caldav-check-dav: Error while checking for OPTIONS at URL https://my.nextcloud.tld/remote.php/dav/calendars/mvsjober/work/: 400 Bad Request
```
The buffer `*org-caldav-debug*` just displays "Started sync."
After the failed sync it opens a buffer displaying the HTTP 400 error:

```
HTTP/1.1 400 Bad Request
Server: nginx
Date: Thu, 18 May 2017 07:07:29 GMT
Content-Type: text/html
Content-Length: 166
Connection: close
```

I have verified that syncing works e.g. with DAVdroid on my phone.

**Comment by dengste** [comment]
OK, so it already fails at the OPTIONS request. What happens when you try with curl, like this:

    curl -D - -X OPTIONS --basic -u mylogin:mypassword URL

That's pretty much what org-caldav is doing.

**Comment by mvsjober** [comment]
Oops! OK, this is embarrassing. It turns out I had an old `.authinfo` file containing old incorrect credentials. Now it works! Very sorry, and thanks for the help :-)

**Comment by hrehfeld** [comment]
after updating I get this: https://gist.github.com/hrehfeld/c8a4efd9760009b8632d1278303bcf7b on the first connect.

Second connect works, but doesn't cope well with renamed org files (events.org -> event.org):

    Non-existent agenda file events.org.  [R]emove from list or [A]bort?
    File was not in list: events.org (not removed)
    org-icalendar--combine-files: Wrong type argument: sequencep, t

When I touch the file, it deletes all its entries and doesn't add those from event.org. When I mv event.org events.org, it adds it back. Should I open an issue?

**Comment by dengste** [comment]
So it's an authorization issue. Do you use an authinfo file? If so,please rename it, restart Emacs and try manual authentication. Please also try the above test with 'curl'.
Regarding the renamed file problem, I'll look into it, no need for a separate issue.

**Comment by hrehfeld** [comment]
curl gets response with 200 OK: https://gist.github.com/hrehfeld/33b53c722aa9e81a9e0e3b72d63bd52a

curl url is calendar name concatenated on what's in org-caldav-calendars :url.

**Comment by dengste** [comment]
OK, here's the same thing in Emacs:

    (switch-to-buffer
     (let ((url-request-method "OPTIONS")
           (url-request-data nil))
       (url-retrieve-synchronously "https://YOUR NEXTCLOUD SERVER/remote.php/dav")))

Start your Emacs with 'emacs -Q', paste this into the scratch buffer and do 'M-x eval-buffer'. This should get answered with a 'HTTP/1.1 200 OK' in the first line. If you're getting a '401' instead, and you're using an .authinfo file, rename it, restart 'emacs -Q' and try again.

**Comment by hrehfeld** [comment]
200 OK: https://gist.github.com/hrehfeld/84a57211a70cda1046b3a1d9bf1bbe57

I have an .authinfo, but the nextcloud isn't in it.

**Comment by dengste** [comment]
Now if you look into org-caldav-check-dav, you'll see that it does the same thing as the above snippet. Did you do the above with 'emacs -Q'? If so, does it also work with your normal Emacs configuration?

**Comment by hrehfeld** [comment]
in 

    $ emacs -q
    (add-to-list 'load-path "~/.emacs.d/elpa/org-caldav-20170517.1157")
    (require 'org-caldav)
    (setq org-caldav-calendars '(...))
    (org-caldav-sync)

I get 

    HTTP/1.1 401 Unauthorized
    Date: Sat, 20 May 2017 09:39:31 GMT
    Server: Apache/2.2.15 (CentOS)
    X-Powered-By: PHP/7.1.0
    Expires: Thu, 19 Nov 1981 08:52:00 GMT
    Cache-Control: no-store, no-cache, must-revalidate
    Pragma: no-cache
    X-XSS-Protection: 1; mode=block
    X-Content-Type-Options: nosniff
    X-Frame-Options: Sameorigin
    X-Robots-Tag: none
    X-Download-Options: noopen
    X-Permitted-Cross-Domain-Policies: none
    Content-Security-Policy: default-src 'none';
    WWW-Authenticate: Basic realm="Nextcloud", Basic realm="Nextcloud", Basic realm="Nextcloud"
    Set-Cookie: ofjdiofj=fdoijf; path=/; HttpOnly
    Set-Cookie: ofijdofij; path=/; secure; HttpOnly
    Connection: close
    Transfer-Encoding: chunked
    Content-Type: application/xml; charset=utf-8
    
    <?xml version="1.0" encoding="utf-8"?>
    <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
      <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
      <s:message>No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured</s:message>
    </d:error>

Second try asks me for non-existant agenda file (because org-directory is not set correctly).

`(setq org-caldav-calendars ... ` is:

    (setq
     my/caldav-baseurl-personal "https://myserver/remote.php/dav/calendars/myusername"
     org-caldav-calendars
     `(
       (:calendar-id "personal"
    				 :files ,(list (concat org-directory "personal.org"))
    				 :inbox ,(concat org-directory "personal_appointments.org")
    				 :url ,my/caldav-baseurl-personal
    				 )
       
       (:calendar-id "events"
    				 :files ,(list (concat org-directory "events.org"))
    				 :inbox ,(concat org-directory "events_inbox.org")
    				 :url ,my/caldav-baseurl-personal
    				 )
       )
     org-caldav-inbox (concat org-directory "appointments.org")
     )

**Comment by dengste** [comment]
I'm still unable to reproduce this, so I'm at a loss. I've now added that if the check for DAV fails org-caldav will try again, so maybe that can be a workaround for this issue...

**Comment by hrehfeld** [comment]
Do you want an account on my server for testing?

Can you log exactly the calls that are made to the messages buffer? I could then try to see which one fails etc. (or do you already know exactly which call fails?)

**Comment by dengste** [comment]
I know which one fails. I have the same issue with Google at the moment. My hunch is that this is a problem with the auth-source library and authinfo files. Can you just for fun put authentication information for your nextcloud server into the authinfo file, as mentioned in the Readme? Does it work then?

**Comment by hrehfeld** [comment]
Okay, with authinfo, I have org-caldav from 2017-05-17, it behaves the same.

I get the 401, and it just works on the next try of org-caldav-sync.

**Comment by hrehfeld** [comment]
And latest version just works. Awesome work, thanks a bunch!

**Comment by dengste** [comment]
And I didn't even fix it! At least not on purpose... Anyway, I think there's a problem with the url package and/or auth-source which leads to getting a buffer with a 401 response, although a second retrieval with authentication was already done. At least that's what I'm sometimes seeing. I'll keep investigating, but I'll close this one for now.

**Comment by dengste** [comment]
I'm pretty sure this is Emacs bug https://debbugs.gnu.org/cgi/bugreport.cgi?bug=10478

I'm not sure however why the problem vanished for you - this bug was never fixed...
