### ISSUE TITLE
Problem with non-ascii and Emacs 25

### ISSUE THREAD

**Issue by DamienCassou** [dengste/org-caldav#96]
I reported a problem on the Emacs mailing list. org-caldav does not work anymore in Emacs 25 when non-ascii characters are present in an org event that must be sent to a remote server (baikal for me):

http://debbugs.gnu.org/cgi/bugreport.cgi?bug=24239

**Comment by dinojr** [comment]
Damien Cassou <notifications@github.com> writes:

> I reported a problem on the Emacs mailing list. org-caldav does not
> work anymore in Emacs 25 when non-ascii characters are present in an
> org event that must be sent to a remote server (baikal for me):
>
> http://debbugs.gnu.org/cgi/bugreport.cgi?bug=24239

I have the same problem when syncing to a google calendar. Switching
back to Emacs 24 would make me recompile a lot of packages (from melpa
mostly), so I'd rather not. Did you manage to get it to work with Emacs
25 ?

Also, I noticed that entries containing items list (like the following
example) don't work, and I don't think there was any trouble with them
before. Maybe it's related ?  Could you please check with an Emacs 24 if
you have one lying around ?

--8<---------------cut here---------------start------------->8---
* Heading
  + first item
  + second item
--8<---------------cut here---------------end--------------->8---

Julien.

**Comment by dinojr** [comment]
Julien Cubizolles <j.cubizolles@free.fr> writes:


> Also, I noticed that entries containing items list (like the following
> example) don't work, and I don't think there was any trouble with them
> before. Maybe it's related ?  Could you please check with an Emacs 24 if
> you have one lying around ?
>
> * Heading
>   + first item
>   + second item

I managed to test it further:

* with Emacs24 item list using "+" don't throw an error even though they
  don't appear in the calendar (which is the intended behaviour I guess)

* with Emacs25-rc1, item list using "+" or "-" thrown the same "error
  "Multibyte text in HTTP request:". However, you can use "=" instead
  but it's not recognized as a item list in org-mode. I didn't try but I
  guess ordered lists are okay.

Julien.

**Comment by DamienCassou** [comment]
In the Emacs bug report, there are explanations regarding what to change in org-caldav. But I didn't manage to get it to work. I don't understand why "+" and "-" wouldn't work.

**Comment by DamienCassou** [comment]
Things seem to be fixed in 25.1. Closing for now as I can't reproduce issue anymore.

**Comment by dinojr** [comment]
The problem is still here with 25.1.50.2. What version did you try ?

**Comment by DamienCassou** [comment]
I'm on `GNU Emacs 25.1.2 (x86_64-unknown-linux-gnu, GTK+ Version 3.20.9) of 2016-09-20`

**Comment by dinojr** [comment]
Thanks, it's working in the  last version (25.1.50.2) from the ubuntu elisp team ppa.
