### ISSUE TITLE
Make it async

### ISSUE THREAD

**Issue by grauschnabel** [dengste/org-caldav#98]
Hi there,

is there a way to make it async, maybe run it with (async-start) - but there it would be needed not to ask the user anything, maybe by setting default values for the questions it asks?

Thanks,
Maartin

**Comment by dengste** [comment]
There's now an option to always/never resume (see 14af011c63b1d5446d769882acafb4cd1157e90a). If there's another thing that creates problems with running it in async, please reopen.

**Comment by grauschnabel** [comment]
Here, this change does not make org-caldav to be in the background.
Maybe this is because sometimes it creates new IDs in the files, and then it askes me to save the file or not before it continues.  `'always` should maybe also save the files?

Here is my config:
```
(require 'org-caldav)
(setq org-caldav-url "https://www.google.com/calendar/dav"
  org-caldav-resume-aborted 'always
  org-icalendar-timezone "Europe/Berlin"
  org-icalendar-include-body nil
      )

(setq org-caldav-calendars
;; some calendar definitions for 4 differente google calendars skipped here
)
;; sync async
(defun org-caldav-async ()
  "syncing org-caldav with async."
  (interactive)
  (async-start
   ;; Sync caldav
   (org-caldav-sync)

   (lambda (result)
     (message "Caldav sync finished with %s" result)))
  )

(global-set-key "\C-cs" 'org-caldav-async)
```
Maybe you can tell me what's wrong?
